### ISSUE TITLE
categorizing questions

### ISSUE THREAD

**Issue by mahlashrifi** [aut-ce/C101#6]
This issue is for organizing and categorizing the homework questions of the basics programming course of previous years.
First, the questions are filled in the [sheet](https://docs.google.com/spreadsheets/d/1SAPncbl116FTfDpmxd_Duw4hvQ280_bsEuRlWDDcNFU/edit?usp=sharing) and after completing each topic relevant md file  should be update . ( from fall-2018 till Spring-2020 is going to be check )

Descriptions :
 Each checked file means that the corresponding question is entered in the sheet

## ***Fall-2018***

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        
   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
    
        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
       
   - [x] **HW-5**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
   
   - [x] **HW-7**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5

## ***Fall-2019***

   - [x] **HW-1**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8
        - [x] P9

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        
   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
    
        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4-1
        - [x] P4-2
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8
       
   - [x] **HW-5**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8
   
   - [x] **HW-7**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        
   - [x] **HW-8**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        
## ***Spring-2019***

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7

   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
   
   - [x] **HW-5**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x] P4
        - [x]  P5

   - [x] **HW-7**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5

 ## ***Spring-2020***

   - [x] **HW-1**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6

   - [x] **HW-2**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8

        
   - [x] **HW-3**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
        - [x] P6
        - [x] P7
        - [x] P8
        - [x] P9
        - [x] P10
        - [x]  P11
        - [x] P12
        - [x] p13
    
        
   - [x] **HW-4**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5
       
   - [x] **HW-6**
        - [x] P1
        - [x] P2
        - [x] P3
        - [x] P4
        - [x]  P5

**Comment by 1995parham** [comment]
Thanks for completing this :raised_back_of_hand:

**Comment by mahlashrifi** [comment]
thanks for your attention 🙏🏻
The issue for terms : fall-2015 / fall-2016 / fall -2017 have been open [here](https://github.com/mahlashrifi/CE101-C/issues/1)
and after categorizing questions of all terms , we will add it to repository as a table of questions .

**Comment by mahlashrifi** [comment]
thanks for your attention 🙏🏻
The issue for terms : fall-2015 / fall-2016 / fall -2017 have been open [here](https://github.com/mahlashrifi/CE101-C/issues/1)
After categorizing questions of all terms , we will add it to repository as a table of questions .
